#!/usr/bin/env bash
# Publish the rendered PR screenshots to a dedicated orphan branch
# (pr-previews) so they can be embedded in the PR comment via raw URLs,
# without cluttering main or the PR's own diff.
#
# Expects: GH_TOKEN, PR_NUMBER, GITHUB_REPOSITORY, GITHUB_SHA, GITHUB_OUTPUT
# and screenshots/{desktop,mobile}.png to exist.
set -euo pipefail

BRANCH="pr-previews"
REPO_URL="https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
BOT_NAME="github-actions[bot]"
BOT_EMAIL="41898282+github-actions[bot]@users.noreply.github.com"

TMP="$(mktemp -d)"

# Check out the existing preview branch, or create it fresh as an orphan.
if git clone --branch "$BRANCH" --single-branch "$REPO_URL" "$TMP" 2>/dev/null; then
  echo "Using existing $BRANCH branch"
else
  echo "Creating fresh orphan $BRANCH branch"
  git clone "$REPO_URL" "$TMP"
  (
    cd "$TMP"
    git checkout --orphan "$BRANCH"
    git rm -rf . >/dev/null 2>&1 || true
    printf '# PR frontpage screenshots\n\nAuto-generated by the "PR Frontpage Screenshots" workflow. Do not edit by hand.\n' > README.md
    git add README.md
    git -c user.name="$BOT_NAME" -c user.email="$BOT_EMAIL" commit -m "Initialise preview branch"
  )
fi

DEST="$TMP/pr-${PR_NUMBER}"
mkdir -p "$DEST"
cp screenshots/desktop.png "$DEST/desktop.png"
cp screenshots/mobile.png "$DEST/mobile.png"

(
  cd "$TMP"
  git add -A
  if git -c user.name="$BOT_NAME" -c user.email="$BOT_EMAIL" \
        commit -m "Screenshots for PR #${PR_NUMBER} (${GITHUB_SHA})"; then
    git push origin "$BRANCH"
  else
    echo "No screenshot changes to commit"
  fi
)

# Cache-bust with the commit SHA so the PR comment always shows the newest
# render rather than a stale cached raw image.
RAW="https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${BRANCH}/pr-${PR_NUMBER}"
{
  echo "desktop_url=${RAW}/desktop.png?sha=${GITHUB_SHA}"
  echo "mobile_url=${RAW}/mobile.png?sha=${GITHUB_SHA}"
} >> "$GITHUB_OUTPUT"

rm -rf "$TMP"
